### PR TITLE
Run catlin when task dir path is passed as argument

### LINKED ISSUE #715: Catlin: Catlin does not validates all the resources passed as an argument in the command
# Expected Behavior

Catlin should validate all the resources passed as an argument in the command

# Actual Behavior

Currently Catlin validates only the first resource in the argument and ignores the remaining resources and not validates them 

For e.g.
```
./catlin validate tmp/catalog/task/buildkit/0.1/buildkit.yaml tmp/catalog/task/build-push-gke-deploy/0.1/build-push-gke-deploy.yaml

HINT : Task: tekton.dev/v1beta1 - name: "buildkit" is missing a readable display name annotation("tekton.dev/displayName")
WARN : Step "build-and-push" uses image "$(params.BUILDKIT_CLIENT_IMAGE)" that contains variables; skipping validation
```

In the above example as we can see Catlin does not validates the second resource

### LINKED ISSUE #716: Catlin: Catlin does not validates the resource even if the folder is passed in the command
# Expected Behavior

Catlin should validate the resource even if the folder is passed in the command

# Actual Behavior

Currently Catlin only supports file validation for a resource and not the folder structure 

For e.g.

```
./catlin validate tmp/catalog/task/buildkit/0.1/

Error: no such file - tmp/catalog/task/buildkit/0.1
```

In the above example Catlin gives an error and not finds the resource file and hence does not validates the resource.
Hence Catlin should validate the resource even if folder is passed in the command

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

With the patch now you can run catlin on directories and also you can
now run catlin on multiple inputs.

Sample execution command would be

```sh
$ catlin validate task/black/0.1 task/maven/0.2
```
- Also added tests for the above command.
- Modified Dockerfile to include bash so that user can use catlin as per their script

Closes #715 
Closes #716 

/cc @SM43 @piyush-garg @vdemeester 

Signed-off-by: vinamra28 <vinjain@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by SM43** [comment]
@vinamra28 Could you please add a few tests? :)

File: catlin/pkg/cmd/validate/validate.go [hunk 1]
```diff
@@ -26,12 +27,40 @@ import (
...
+
+	if info.IsDir() {
+
+		files, err := getFilesInDir(path)
+		if err != nil {
+			return false
+		}
+
+		for _, file := range files {
+			if filepath.Ext(file.Name()) == ".yaml" {
```
Comment (PuneetPunamiya) [inline catlin/pkg/cmd/validate/validate.go:56]: Since we have the directory name as the filename shouldn't we just check for the name of the file with the extension of yaml ?? wdyt
