### PR TITLE
Fix failing kind cluster start and update docs

### LINKED ISSUE #2486: Script `tekton_in_kind.sh` fails to start kind cluster in Docker because of an unrecognized feature gate.
# Expected Behavior

Following this [guide](https://github.com/tektoncd/plumbing/tree/main/hack#tekton_in_kindsh) I expect a running kind cluster with running Tekton components.

I am using Linux Fedora 40.

# Actual Behavior

Installation fails when kind tries starting the control-plane.

# Steps to Reproduce the Problem

1. Be on Linux Fedora 40.
2. Execute from `plumbing` root directory: `./hack/tekton_in_kind.sh -k`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.32.2
  Kustomize Version: v5.5.0
  ```

- Main error thrown by kubelet in tekton-control-plane

  ```
  Mar 05 13:38:57 tekton-control-plane kubelet[1422]: panic: failed to merge global and in-flight KubeletConfiguration while setting defaults, error: unrecognized feature gate: EphemeralContainers
  ```

- Full error output in terminal

```
No kind clusters found.
Creating cluster "tekton" ...
 ✓ Ensuring node image (kindest/node:v1.32.2) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
Deleted nodes: ["tekton-control-plane" "tekton-worker" "tekton-worker2"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged tekton-control-plane kubeadm init --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0305 13:37:36.023954     236 initconfiguration.go:261] loading configuration from "/kind/kubeadm.conf"
W0305 13:37:36.024528     236 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "ClusterConfiguration"). Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0305 13:37:36.025003     236 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "InitConfiguration"). Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0305 13:37:36.025357     236 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "JoinConfiguration"). Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0305 13:37:36.025595     236 initconfiguration.go:361] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.32.2
I0305 13:37:36.026863     236 certs.go:112] creating a new certificate authority for ca
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
I0305 13:37:36.149959     236 certs.go:473] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost tekton-control-plane] and IPs [10.96.0.1 172.18.0.3 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I0305 13:37:36.656727     236 certs.go:112] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I0305 13:37:36.771324     236 certs.go:473] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I0305 13:37:36.947964     236 certs.go:112] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I0305 13:37:37.262109     236 certs.go:473] validating certificate period for etcd/ca certificate
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost tekton-control-plane] and IPs [172.18.0.3 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost tekton-control-plane] and IPs [172.18.0.3 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I0305 13:37:37.965153     236 certs.go:78] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I0305 13:37:38.125602     236 kubeconfig.go:111] creating kubeconfig file for admin.conf
[kubeconfig] Writing "admin.conf" kubeconfig file
I0305 13:37:38.362680     236 kubeconfig.go:111] creating kubeconfig file for super-admin.conf
[kubeconfig] Writing "super-admin.conf" kubeconfig file
I0305 13:37:38.479756     236 kubeconfig.go:111] creating kubeconfig file for kubelet.conf
[kubeconfig] Writing "kubelet.conf" kubeconfig file
I0305 13:37:38.654963     236 kubeconfig.go:111] creating kubeconfig file for controller-manager.conf
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
I0305 13:37:38.714896     236 kubeconfig.go:111] creating kubeconfig file for scheduler.conf
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I0305 13:37:38.794785     236 local.go:66] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I0305 13:37:38.794817     236 manifests.go:104] [control-plane] getting StaticPodSpecs
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I0305 13:37:38.795036     236 certs.go:473] validating certificate period for CA certificate
I0305 13:37:38.795115     236 manifests.go:130] [control-plane] adding volume "ca-certs" for component "kube-apiserver"
I0305 13:37:38.795123     236 manifests.go:130] [control-plane] adding volume "etc-ca-certificates" for component "kube-apiserver"
I0305 13:37:38.795127     236 manifests.go:130] [control-plane] adding volume "k8s-certs" for component "kube-apiserver"
I0305 13:37:38.795131     236 manifests.go:130] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-apiserver"
I0305 13:37:38.795137     236 manifests.go:130] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-apiserver"
I0305 13:37:38.795851     236 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
I0305 13:37:38.795862     236 manifests.go:104] [control-plane] getting StaticPodSpecs
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I0305 13:37:38.796047     236 manifests.go:130] [control-plane] adding volume "ca-certs" for component "kube-controller-manager"
I0305 13:37:38.796055     236 manifests.go:130] [control-plane] adding volume "etc-ca-certificates" for component "kube-controller-manager"
I0305 13:37:38.796077     236 manifests.go:130] [control-plane] adding volume "flexvolume-dir" for component "kube-controller-manager"
I0305 13:37:38.796082     236 manifests.go:130] [control-plane] adding volume "k8s-certs" for component "kube-controller-manager"
I0305 13:37:38.796086     236 manifests.go:130] [control-plane] adding volume "kubeconfig" for component "kube-controller-manager"
I0305 13:37:38.796091     236 manifests.go:130] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-controller-manager"
I0305 13:37:38.796109     236 manifests.go:130] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-controller-manager"
I0305 13:37:38.796774     236 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
I0305 13:37:38.796784     236 manifests.go:104] [control-plane] getting StaticPodSpecs
[control-plane] Creating static Pod manifest for "kube-scheduler"
I0305 13:37:38.796970     236 manifests.go:130] [control-plane] adding volume "kubeconfig" for component "kube-scheduler"
I0305 13:37:38.797414     236 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
I0305 13:37:38.797423     236 kubelet.go:70] Stopping the kubelet
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
I0305 13:37:38.969848     236 loader.go:402] Config loaded from file:  /etc/kubernetes/admin.conf
I0305 13:37:38.970240     236 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0305 13:37:38.970253     236 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0305 13:37:38.970259     236 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0305 13:37:38.970263     236 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests"
[kubelet-check] Waiting for a healthy kubelet at http://127.0.0.1:10248/healthz. This can take up to 4m0s
[kubelet-check] The kubelet is not healthy after 4m0.001047694s

Unfortunately, an error has occurred:
        The HTTP call equal to 'curl -sSL http://127.0.0.1:10248/healthz' returned error: Get "http://127.0.0.1:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused


This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
could not initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:112
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:122
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:129
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_amd64.s:1700
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:262
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:129
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_amd64.s:1700
```

### LINKED ISSUE #2522: Script `tekton_in_kind.sh` fails to start kind cluster in Podman because of a `inotify_init: too many open files` kubelet error.
# Expected Behavior

Following this [guide](https://github.com/tektoncd/plumbing/tree/main/hack#tekton_in_kindsh) I expect a running kind cluster in Podman with running Tekton components.

I am using Linux Fedora 40.

# Actual Behavior

Installation fails when kind tries to join the worker nodes.

# Steps to Reproduce the Problem

1. Be on Linux Fedora 40.
2. Execute from `plumbing` root directory: `./hack/tekton_in_kind.sh`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.32.2
  Kustomize Version: v5.5.0
  ```

- Main error thrown by kubelet in tekton-worker

  ```
  kubelet[510]: E0319 16:49:49.963674     510 manager.go:294] Registration of the raw container factory failed: inotify_init: too many open files
  kubelet[510]: E0319 16:49:49.964127     510 kubelet.go:1632] "Failed to start cAdvisor" err="inotify_init: too many open files"
  systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
  systemd[1]: kubelet.service: Failed with result 'exit-code'.
  ```
- Full error output in terminal

```sh
./hack/tekton_in_kind.sh
Using container runtime: podman
fd94d8d8ac2e25acb8d5c767386e5c3fc8c427f5575c88ff6c1a2fcf6ee429d0
Registry started...
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
No kind clusters found.
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
Creating cluster "tekton" ...
 ✓ Ensuring node image (kindest/node:v1.32.2) 🖼
 ✓ Preparing nodes 📦 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✗ Joining worker nodes 🚜
Deleted nodes: ["tekton-control-plane" "tekton-worker" "tekton-worker2"]
ERROR: failed to create cluster: failed to join node with kubeadm: command "podman exec --privileged tekton-worker kubeadm join --config /kind/kubeadm.conf --v=6" failed with error: exit status 1
Command Output: I0305 08:37:40.645728     204 join.go:421] [preflight] found NodeName empty; using OS hostname as NodeName
I0305 08:37:40.645815     204 joinconfiguration.go:83] loading configuration from "/kind/kubeadm.conf"
W0305 08:37:40.646506     204 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "JoinConfiguration"). Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
I0305 08:37:40.647118     204 controlplaneprepare.go:225] [download-certs] Skipping certs download
I0305 08:37:40.647133     204 join.go:551] [preflight] Discovering cluster-info
I0305 08:37:40.647144     204 token.go:72] [discovery] Created cluster-info discovery client, requesting info from "tekton-control-plane:6443"
I0305 08:37:40.647297     204 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0305 08:37:40.647315     204 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0305 08:37:40.647323     204 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0305 08:37:40.647338     204 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0305 08:37:40.647723     204 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "abcdef"
I0305 08:37:40.655380     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 7 milliseconds
I0305 08:37:40.655576     204 token.go:250] [discovery] Retrying due to error: could not find a JWS signature in the cluster-info ConfigMap for token ID "abcdef"
I0305 08:37:45.651737     204 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "abcdef"
I0305 08:37:45.658451     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 5 milliseconds
I0305 08:37:45.658935     204 token.go:114] [discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "tekton-control-plane:6443"
I0305 08:37:45.658944     204 discovery.go:53] [discovery] Using provided TLSBootstrapToken as authentication credentials for the join process
I0305 08:37:45.658956     204 join.go:565] [preflight] Fetching init configuration
I0305 08:37:45.658961     204 join.go:652] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the "kubeadm-config" ConfigMap in namespace "kube-system"...
[preflight] Use 'kubeadm init phase upload-config --config your-config.yaml' to re-upload it.
I0305 08:37:45.665103     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s 200 OK in 5 milliseconds
I0305 08:37:45.666397     204 kubeproxy.go:55] attempting to download the KubeProxyConfiguration from ConfigMap "kube-proxy"
I0305 08:37:45.667897     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 200 OK in 1 milliseconds
I0305 08:37:45.670426     204 kubelet.go:74] attempting to download the KubeletConfiguration from ConfigMap "kubelet-config"
I0305 08:37:45.672012     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 200 OK in 1 milliseconds
I0305 08:37:45.673975     204 initconfiguration.go:115] skip CRI socket detection, fill with the default CRI socket unix:///var/run/containerd/containerd.sock
I0305 08:37:45.674184     204 interface.go:432] Looking for default routes with IPv4 addresses
I0305 08:37:45.674191     204 interface.go:437] Default route transits interface "eth0"
I0305 08:37:45.674273     204 interface.go:209] Interface eth0 is up
I0305 08:37:45.674308     204 interface.go:257] Interface "eth0" has 3 addresses :[10.89.0.3/24 fc00:8866:27d0:bd7e::3/64 fe80::432:7fff:fe0b:d34e/64].
I0305 08:37:45.674331     204 interface.go:224] Checking addr  10.89.0.3/24.
I0305 08:37:45.674338     204 interface.go:231] IP found 10.89.0.3
I0305 08:37:45.674345     204 interface.go:263] Found valid IPv4 address 10.89.0.3 for interface "eth0".
I0305 08:37:45.674351     204 interface.go:443] Found active IP 10.89.0.3
I0305 08:37:45.674640     204 kubelet.go:183] [kubelet-start] writing bootstrap kubelet config file at /etc/kubernetes/bootstrap-kubelet.conf
I0305 08:37:45.678455     204 kubelet.go:198] [kubelet-start] writing CA certificate at /etc/kubernetes/pki/ca.crt
I0305 08:37:45.678572     204 kubelet.go:214] [kubelet-start] Checking for an existing Node in the cluster with name "tekton-worker" and status "Ready"
I0305 08:37:45.680515     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:37:45.680577     204 kubelet.go:229] [kubelet-start] Stopping the kubelet
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-check] Waiting for a healthy kubelet at http://127.0.0.1:10248/healthz. This can take up to 4m0s
[kubelet-check] The kubelet is healthy after 6.505697266s
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap
I0305 08:37:52.508588     204 loader.go:402] Config loaded from file:  /etc/kubernetes/kubelet.conf
I0305 08:37:52.511928     204 loader.go:402] Config loaded from file:  /etc/kubernetes/kubelet.conf
I0305 08:37:52.512555     204 cert_rotation.go:140] Starting client certificate rotation controller
I0305 08:37:52.514241     204 kubelet.go:337] [kubelet-start] preserving the crisocket information for the node
I0305 08:37:52.514563     204 patchnode.go:31] [patchnode] Uploading the CRI Socket information "unix:///run/containerd/containerd.sock" to the Node API object "tekton-worker" as an annotation
I0305 08:37:52.554552     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 39 milliseconds
I0305 08:37:53.019536     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:37:53.519525     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:37:54.024797     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 9 milliseconds
I0305 08:37:54.519932     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:55.019213     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:55.525098     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 8 milliseconds
I0305 08:37:56.019758     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:56.519185     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:57.031977     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 16 milliseconds
I0305 08:37:57.519473     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:58.016985     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:37:58.520868     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 5 milliseconds
I0305 08:37:59.019962     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:37:59.517770     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:00.027146     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 11 milliseconds
I0305 08:38:00.516574     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:01.020713     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:01.516734     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:02.019250     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:02.519315     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:03.033784     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 17 milliseconds
I0305 08:38:03.519007     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:04.017385     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:04.517397     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:05.019481     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:05.519832     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:06.024471     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 8 milliseconds
I0305 08:38:06.521389     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 5 milliseconds
I0305 08:38:07.020144     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:07.517198     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:08.020141     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:08.519834     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:09.034195     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 17 milliseconds
I0305 08:38:09.520029     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:10.017441     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:10.520314     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:11.017385     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:11.517438     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:12.022941     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:12.516816     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:13.019893     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:13.529997     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 13 milliseconds
I0305 08:38:14.020101     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:14.520194     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:15.020148     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:15.520087     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:16.020102     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:16.520385     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:17.020828     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:17.520195     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:18.024220     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:18.519182     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:19.020610     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:19.522900     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:20.019605     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:20.519363     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:21.039623     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 24 milliseconds
I0305 08:38:21.520357     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:22.020414     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:22.519391     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:23.020028     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:23.519993     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:24.038795     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 22 milliseconds
I0305 08:38:24.520055     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:25.017796     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:25.516552     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:26.019847     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:26.517202     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:27.029368     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 13 milliseconds
I0305 08:38:27.520529     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:28.025904     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 9 milliseconds
I0305 08:38:28.520006     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:29.020499     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:29.519925     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:30.042872     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 25 milliseconds
I0305 08:38:30.520288     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:31.019047     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 2 milliseconds
I0305 08:38:31.525739     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 10 milliseconds
I0305 08:38:32.019771     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:32.519823     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:33.033164     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 16 milliseconds
I0305 08:38:33.520147     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:34.019752     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:34.519499     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:35.019976     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:35.520890     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 5 milliseconds
I0305 08:38:36.017917     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:36.519517     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:37.019423     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:37.517086     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 1 milliseconds
I0305 08:38:38.020953     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:38.520356     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:39.048880     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 30 milliseconds
I0305 08:38:39.519592     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:40.020709     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:40.534031     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 15 milliseconds
I0305 08:38:41.020334     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:41.520641     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:42.034909     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 18 milliseconds
I0305 08:38:42.519953     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:43.023480     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 7 milliseconds
I0305 08:38:43.519486     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:44.020221     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:44.520581     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:45.022909     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:45.520647     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:46.020371     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:46.522211     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:47.020229     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:47.520641     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:48.021510     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 5 milliseconds
I0305 08:38:48.520270     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:49.020236     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:49.520849     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:50.019998     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 3 milliseconds
I0305 08:38:50.520093     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:51.023180     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 6 milliseconds
I0305 08:38:51.520406     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:52.019722     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
I0305 08:38:52.519753     204 round_trippers.go:560] GET https://tekton-control-plane:6443/api/v1/nodes/tekton-worker?timeout=10s 404 Not Found in 4 milliseconds
nodes "tekton-worker" not found
error writing CRISocket for this node
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runKubeletWaitBootstrapPhase
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/kubelet.go:339
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runKubeletStartJoinPhase
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/kubelet.go:274
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:185
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_amd64.s:1700
error execution phase kubelet-start
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:262
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:185
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_amd64.s:1700
```

### LINKED ISSUE #2523: Script `tekton_in_kind.sh` fails to connect registry with kind cluster in Podman.
# Expected Behavior

Following this [guide](https://github.com/tektoncd/plumbing/tree/main/hack#tekton_in_kindsh) I expect a running registry connected to a kind cluster in Podman with running Tekton components.

I am using Linux Fedora 40.

# Actual Behavior

The cluster starts but the registry can not be connected to the "kind" network.

# Steps to Reproduce the Problem

1. Be on Linux Fedora 40.
2. Increase `inotify` limits following the steps [here](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files) to be able to start the cluster.
3. Execute from `plumbing` root directory: `./hack/tekton_in_kind.sh`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.32.2
  Kustomize Version: v5.5.0
  ```

- Error output

  ```
  Error: "pasta" is not supported: invalid network mode
  ```

### PR DESCRIPTION
**Pull request by twoGiants**
# Changes

When starting the kind cluster using docker with the previous configuration the control-plane kubelet stopped with an error not knowing a feature gate for "EphemeralContainers". This feature is stable since kubernetes 1.24 so this configuration was safely removed.

Closes #2486.

Starting the kind cluster using podman failed when joining the worker-nodes. This is fixed by a minor change on the host. A [troubleshooting](https://github.com/tektoncd/plumbing/pull/2487/files#diff-6a33146cb453cc624d7fa8ebedf1e5f7105e5dc8c835badc012760e18853eb7bR93) section was added to the readme with a link to the fix.

Closes #2522.

Once the kind cluster started using podman the registry could not be connected. This issue was resolved by changing the network mode to "bridge" which is also used in the [guide](https://kind.sigs.k8s.io/docs/user/local-registry/#create-a-cluster-and-registry) on the kind website.

Closes #2523.

If podman and docker runtimes are installed on the host the script does not behave as expected. Starting it using podman will start the registry in podman and the kind cluster in docker. It was updated to always start the registry and the cluster using the same runtime.

Added logs with info about successful and next steps which helps to debug when something fails. Raised the timeouts in the `kubectl wait` command to `600s`, `120s` were not enough.

As of this writing the support for podman in kind is [experimental](https://github.com/kubernetes-sigs/kind/issues/1778). This information was added to the documentation.

Fixed broken links in CONTRIBUTING.md. Updated cluster installation docs in DEVELOPMENT.md to use latest kind and newer go versions, added links to kustomize and tkn installation guides.

/kind bug
/kind documentation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by twoGiants** [comment]
Thanks for approving @vdemeester! After reading the [code review process](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process) I believe there is an `/approve` comment from you missing. This is a kind reminder to set an `/approve` comment and then it will be merged. Thanks again!

**Comment by afrittoli** [comment]
> Thanks for approving @vdemeester! After reading the [code review process](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process) I believe there is an `/approve` comment from you missing. This is a kind reminder to set an `/approve` comment and then it will be merged. Thanks again!

@twoGiants Thanks for pointing that out. We have two review types of labels, "approved" and "lgtm". These two can be given by two different reviewers (or in some cases by the same one), at the reviewer's discretion. 
For some repos, like `tektoncd/pipeline`, we require in most cases two have two different reviewers.

File: hack/tekton_in_kind.sh [hunk 1]
```diff
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 set -e -o pipefail
 
-declare TEKTON_PIPELINE_VERSION TEKTON_TRIGGERS_VERSION TEKTON_DASHBOARD_VERSION CONTAINER_RUNTIME
+declare TEKTON_PIPELINE_VERSION TEKTON_TRIGGERS_VERSION TEKTON_DASHBOARD_VERSION
```
Comment (afrittoli) [inline hack/tekton_in_kind.sh:4]: I would rather keep the `podman` option in.
The docker license does not allow many individuals to use docker on their laptop, `podman` is the only open source alternative and it works well for that is required with Tekton.

**Review by afrittoli — COMMENTED** [review]
Thanks for your PR!
It mostly looks good, the only request from me would be to keep `podman` support directly in the script intead of requiring setting environment variables to use it.

File: hack/tekton_in_kind.sh (hunk 1 above)
Comment (twoGiants) [reply hack/tekton_in_kind.sh]: Done.

**Review by afrittoli — COMMENTED** [review]
Thanks for the detailed update and troubleshooting section. 
/lgtm
